baseurl = "https://capra.cs.cornell.edu/diospyros/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Diospyros"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[markup.goldmark.renderer]
unsafe= true

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Search-aided Vectorization"
  #mainSections = ["post","posts"]
  #logo = "img/x.png" # Expecting square dimensions
  favicon = "img/x.png"
  dateFormat = "January 2, 2006"
  useHLJS = false
  showRelatedPosts = true
  since="2020"

#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Rachit Nigam"
  website = "rachitnigam.com"

[[menu.main]]
    name = "Demo"
    url = ""
    weight = 10
