baseurl = "https://capra.cs.cornell.edu/dahlia/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Dahlia"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[markup.goldmark.renderer]
unsafe= true

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "A Language for Predictable Accelerator Design"
  #mainSections = ["post","posts"]
  logo = "img/dahlia-logo.png" # Expecting square dimensions
  favicon = "img/dahlia-logo.png"
  dateFormat = "January 2, 2006"
  useHLJS = false
  showRelatedPosts = true
  since="2020"

#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Rachit Nigam"
  website = "rachitnigam.com"

[[menu.main]]
    name = "Demo"
    url = ""
    weight = 10

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 20

[[menu.main]]
    name = "Research"
    url = "page/research/"
    weight = 25

[[menu.main]]
    name = "Code"
    url = "https://github.com/cucapra/dahlia"
    weight = 30

[[menu.main]]
    name = "Documentation"
    url = "https://capra.cs.cornell.edu/fuse"
    weight = 40
