ver = "0.2.3"

[[tests]]
name = "Intermediate compilation"
paths = [ "tests/vec-lang-compile/*.rkt" ]
cmd = "./dios --no-compile {}"

[[tests]]
name = "C compilation"
paths = [ "tests/c-compile/*.rkt" ]
cmd = "./dios --supress-git {}"
