(prog
 (list
  (vec-extern-decl 'A 4 'extern-input)
  (vec-extern-decl 'B 4 'extern-input)
  (vec-extern-decl 'C 4 'extern-output)
  (vec-decl 'reg-C 4)
  (vec-load 'C_0_4 'C 0 4)
  (vec-const 'shuf0-0 '#(2 0 1 2) 'int)
  (vec-const 'shuf1-0 '#(0 1 2 3) 'int)
  (vec-shuffle 'reg-A 'shuf0-0 '(A))
  (vec-shuffle 'reg-B 'shuf1-0 '(B))
  (vec-write 'reg-C 'C_0_4)
  (vec-app 'out 'vec-add '(reg-A reg-B))
  (vec-write 'C_0_4 'out)
  (vec-const 'shuf0-1 '#(0 1 2 3) 'int)
  (vec-const 'shuf1-1 '#(0 1 2 3) 'int)
  (vec-shuffle 'reg-A 'shuf0-1 '(A))
  (vec-shuffle 'reg-B 'shuf1-1 '(B))
  (vec-write 'reg-C 'C_0_4)
  (vec-app 'out 'vec-add '(reg-A reg-B))
  (vec-write 'C_0_4 'out)
  (vec-store 'C 'C_0_4 0 4)))
