(prog
  (list
    (vec-extern-decl 'I 8 'extern-input)
    (vec-extern-decl 'F 4 'extern-input)
    (vec-extern-decl 'O 8 'extern-output)
    (vec-const 'Z '#(0))
    (vec-load 'O_0_4 'O 0 4)
    (vec-load 'O_4_8 'O 4 8)
    (vec-const 'shuf0-0 '#(8 9 11 8))
    (vec-const 'shuf1-0 '#(3 3 3 0))
    (vec-shuffle 'reg-I 'shuf0-0 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-0 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_0_4)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_0_4 'out)
    (vec-const 'shuf0-1 '#(11 1 8 10))
    (vec-const 'shuf1-1 '#(0 6 4 6))
    (vec-shuffle 'reg-I 'shuf0-1 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-1 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_4_8)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_4_8 'out)
    (vec-const 'shuf0-2 '#(5 3 4 5))
    (vec-const 'shuf1-2 '#(2 5 6 5))
    (vec-shuffle 'reg-I 'shuf0-2 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-2 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_4_8)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_4_8 'out)
    (vec-const 'shuf0-3 '#(3 11 5 5))
    (vec-const 'shuf1-3 '#(0 3 0 7))
    (vec-shuffle 'reg-I 'shuf0-3 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-3 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_0_4)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_0_4 'out)
    (vec-const 'shuf0-4 '#(6 9 5 11))
    (vec-const 'shuf1-4 '#(1 7 6 2))
    (vec-shuffle 'reg-I 'shuf0-4 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-4 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_4_8)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_4_8 'out)
    (vec-const 'shuf0-5 '#(7 11 7 3))
    (vec-const 'shuf1-5 '#(6 3 5 6))
    (vec-shuffle 'reg-I 'shuf0-5 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-5 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_0_4)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_0_4 'out)
    (vec-const 'shuf0-6 '#(0 0 7 7))
    (vec-const 'shuf1-6 '#(5 4 7 7))
    (vec-shuffle 'reg-I 'shuf0-6 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-6 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_0_4)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_0_4 'out)
    (vec-const 'shuf0-7 '#(0 11 4 2))
    (vec-const 'shuf1-7 '#(5 2 4 4))
    (vec-shuffle 'reg-I 'shuf0-7 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-7 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_4_8)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_4_8 'out)
    (vec-const 'shuf0-8 '#(1 3 4 9))
    (vec-const 'shuf1-8 '#(4 1 5 1))
    (vec-shuffle 'reg-I 'shuf0-8 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-8 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_0_4)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_0_4 'out)
    (vec-const 'shuf0-9 '#(1 10 3 3))
    (vec-const 'shuf1-9 '#(2 3 7 3))
    (vec-shuffle 'reg-I 'shuf0-9 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-9 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_0_4)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_0_4 'out)
    (vec-const 'shuf0-10 '#(0 7 5 7))
    (vec-const 'shuf1-10 '#(3 5 4 7))
    (vec-shuffle 'reg-I 'shuf0-10 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-10 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_0_4)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_0_4 'out)
    (vec-const 'shuf0-11 '#(4 4 7 6))
    (vec-const 'shuf1-11 '#(3 5 7 6))
    (vec-shuffle 'reg-I 'shuf0-11 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-11 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_4_8)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_4_8 'out)
    (vec-const 'shuf0-12 '#(7 2 5 7))
    (vec-const 'shuf1-12 '#(0 4 6 3))
    (vec-shuffle 'reg-I 'shuf0-12 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-12 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_4_8)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_4_8 'out)
    (vec-const 'shuf0-13 '#(5 1 11 3))
    (vec-const 'shuf1-13 '#(7 3 2 6))
    (vec-shuffle 'reg-I 'shuf0-13 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-13 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_0_4)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_0_4 'out)
    (vec-const 'shuf0-14 '#(5 5 7 6))
    (vec-const 'shuf1-14 '#(7 3 2 6))
    (vec-shuffle 'reg-I 'shuf0-14 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-14 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_4_8)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_4_8 'out)
    (vec-const 'shuf0-15 '#(3 9 4 1))
    (vec-const 'shuf1-15 '#(7 6 1 4))
    (vec-shuffle 'reg-I 'shuf0-15 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-15 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_0_4)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_0_4 'out)
    (vec-const 'shuf0-16 '#(2 9 3 7))
    (vec-const 'shuf1-16 '#(1 3 2 4))
    (vec-shuffle 'reg-I 'shuf0-16 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-16 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_0_4)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_0_4 'out)
    (vec-const 'shuf0-17 '#(7 4 11 11))
    (vec-const 'shuf1-17 '#(5 5 2 3))
    (vec-shuffle 'reg-I 'shuf0-17 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-17 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_0_4)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_0_4 'out)
    (vec-const 'shuf0-18 '#(7 1 2 5))
    (vec-const 'shuf1-18 '#(5 6 3 1))
    (vec-shuffle 'reg-I 'shuf0-18 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-18 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_0_4)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_0_4 'out)
    (vec-const 'shuf0-19 '#(10 7 6 0))
    (vec-const 'shuf1-19 '#(2 1 3 5))
    (vec-shuffle 'reg-I 'shuf0-19 '(I Z))
    (vec-shuffle 'reg-F 'shuf1-19 '(F Z))
    (vec-decl 'reg-O 4)
    (vec-write 'reg-O 'O_4_8)
    (vec-app 'out 'vec-mac '(reg-O reg-I reg-F))
    (vec-write 'O_4_8 'out)
    (vec-store 'O 'O_0_4 0 4)
    (vec-store 'O 'O_4_8 4 8)))
